FROM mjohnson459/ros:kinetic-robot

#switch on systemd init system in container
ENV INITSYSTEM on

RUN apt-get -q update && apt-get install -yq --no-install-recommends \
	build-essential \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ./catkin_ws /catkin_ws
WORKDIR /catkin_ws

RUN /ros_entrypoint.sh catkin_make install -DCMAKE_INSTALL_PREFIX=/opt/ros/kinetic/

CMD ["roslaunch", "hello_world", "hello_world.launch"]
