name: spare-parts
version: 0.2
summary: Rust for robots test
description: |
  Rust for robots?

grade: devel
confinement: devmode
architectures: [armhf]

apps:
  marvin:
    command: marvin
    daemon: simple
    plugs: [network-bind, i2c]

parts:
  marvin:
    source: .
    plugin: rust

